services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "exchange_rates"
    ports:
      - "5435:5432"

  app:
    build: .
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "qwerty"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "exchange_rates"
    ports:
      - "8080:8080"
    expose:
      - "8080/tcp"
    depends_on:
      - postgres
      - migrate

  migrate:
    image: migrate/migrate
    volumes:
      - ./schema/:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:qwerty@postgres:5432/exchange_rates?sslmode=disable", "up" ]
    depends_on:
      - postgres


