services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "exchange_rates"
    ports:
      - "5435:5432"

  app:
    build: .
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "qwerty"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "exchange_rates"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

